### PR TITLE
Fix #6264 MOLGENIS documentation should warn that you should use the AJP protocol from proxies

### LINKED ISSUE #6264: MOLGENIS documentation should warn that you should use the AJP protocol from proxies
### How to Reproduce
- Go to the installation instruction for MOLGENIS in the manual

### Expected behavior
- The installation instructions should note special considerations such as requiring AJP if you use a proxy in front of Tomcat
- We should refer to AJP documentation such as http://httpd.apache.org/docs/2.4/mod/mod_proxy_ajp.html on how to configure things instead of writing extensive documentation

### Observed behavior
- The installation instructions do not tell this.

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

**Comment by marikaris** [comment]
There is now a sign in button, but I cannot click it haha.

**Comment by fdlk** [comment]
In general, I think that a webapp shouldn't worry about how it's being deployed and only list the restrictions it makes on how it can be deployed. (In our case, things like that you must deploy it as the root app and that we include the jdbc postgres driver both of which are a bit of a nono.)

I don't have a clear overview of the advantages and benefits of using AJP when you proxy but I would expect that the benefits of using AJP are actually small. We've had an issue (#2816) with the protocol because it is more stateful than simple HTTP.

I would prefer to alert the sysops who deploy a molgenis to the option of using AJP than demand that they use it which would suggest that molgenis doesn't work properly without it. If they prefer to run it behind an existing nginx, for instance, that will work great as well and we shouldn't discourage them from it.

**Comment by dennishendriksen** [comment]
I don't think this section should be added to our documentation since it is specific for the deployment environment.

**Comment by dennishendriksen** [comment]
@fdlk AJP was introduced in our VM SOP late 2014 to resolve the issue where the web application was not able to determine the request URI (more specifically: the 'HTTP activation URL')

**Comment by Mark-de-Haan** [comment]
Then we close this.

**Pull request closed without merging**
