### PR TITLE
Refactor one-to-many to enforce required xref

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Unit tests
- [ ] Updated testplan

### CODE REVIEW

**Comment by bartcharbon** [comment]
ONE_TO_MANY shows up in the mapping service UI.
Creating an instance of an entity with the ONE_TO_MANY "filled" from java or REST will ignore this ONE_TO_MANY value (theory for now, will verify...)

**Comment by Mark-de-Haan** [comment]
Are these changes also in #5325 ?

**Comment by dennishendriksen** [comment]
Yes

**Comment by tommydeboer** [comment]
Can't see, find and select entities in xref/onetomany dropdowns in forms when label attribute of these entities is empty. Not sure if this is working as intended, but I tried the same with xref/mref and there I am able to find and select entities.

**Comment by dennishendriksen** [comment]
@tommydeboer cannot reproduce, I used the following data:
[onetomany-authorbook-nolabelattrs.zip](https://github.com/molgenis/molgenis/files/523617/onetomany-authorbook-nolabelattrs.zip)
onetomany-nolabelattr-author_form
onetomany-nolabelattr-authors
onetomany-nolabelattr-book_form
onetomany-nolabelattr-books

**Pull request merged**
