### PR TITLE
Fix #5223 The molgenis.addAll(entityName, dataFrame) function in R is extremely slow

### LINKED ISSUE #5223: The molgenis.addAll(entityName, dataFrame) function in R is extremely slow
#### Reproduce
- import [model_issue_5223.xlsx](https://github.com/molgenis/molgenis/files/596995/model_issue_5223.xlsx)

- Extract the R script and open it in Rstudio [rscript_issue_5223.R.zip](https://github.com/molgenis/molgenis/files/597025/rscript_issue_5223.R.zip)

- Edit the URL for fetching the molgenis.R depending on which server you are reproducing the issue

- Run the script

#### Expected
Speed is similar to importer or Rest API and it will take a few seconds

#### Observed
It inserts about 5 rows / second

### PR DESCRIPTION
**Pull request by marikaris**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [ ] Code unit/integration/system tested
- [x] User documentation updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
When running with the original issue demo set + script, I run into a 415 Unsupported Media Type error

Script: 
```
library(RCurl)
library(httr)

# For local host
source("http://localhost:8080/molgenis.R")
molgenis.login("admin", "admin")

# Use repeat to create dummy data
#CHROM POS Gene Transcript cDNA Type Location Exon Effect Protein Classification Comments
chrom <- rep(1, 1000) 
pos <-  rep(123456789, 1000) 
gene <- rep("BRCA2", 1000)
transcript <- rep("transcript_123", 1000)
cDNA <- rep("A>T", 1000)
Type <- rep("CONSERVATION", 1000)
Location <- rep("MOLGENIS", 1000)
Exon <- rep("123_3Exon", 1000)
Effect <- rep("Does a lot of things", 1000)
Protein <- rep("ATP", 1000)
Classification <- rep("Pathogenic", 1000)
Comments <- rep("This is a comment", 1000)

dataframe <- data.frame(chrom, pos, gene, transcript, cDNA, Type, Location, Exon, Effect, Protein, Classification, Comments)
colnames(dataframe) <- c("#CHROM", "POS", "Gene", "Transcript", "cDNA", "Type", "Location", "Exon", "Effect", "Protein", "Classification", "Comments")

molgenis.addAll("base_LAB_MODEL", dataframe)
```

**Comment by fdlk** [comment]
Tested with 1000 rows, which is the maximum amount that the mass upload method allows, on localhost. Works like a charm, and finishes in just 2 seconds. Would be nice if the method also splits larger data sets into chunks of 1000. Not entirely sure how hard this is to achieve.

**Comment by fdlk** [comment]
Tested it, works like a charm on my local machine!

**Comment by fdlk** [comment]
Tested on molgenis01, works like a charm!

**Pull request merged**
