### PR TITLE
M4036: As RD-connect and BBMRI-ERIC I want to automatic ingest of Excel/CSV file

### PR DESCRIPTION
**Pull request by erwinwinder**
Also fix needed for this issue: github issue #4424 Can't set a reference to EntityMDMD or AttributeMDMD

### CODE REVIEW

**Comment by tommydeboer** [comment]
Deleting an automatic import fails:

```
Error! PreparedStatementCallback; SQL [DELETE FROM `FileIngest` WHERE `id` = ?]; Cannot delete or update a parent row: a foreign key constraint fails (`omx`.`fileingestjobmetadata`, CONSTRAINT `fileingestjobmetadata_ibfk_3` FOREIGN KEY (`fileIngest`) REFERENCES `FileIngest` (`id`)); nested exception is java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`omx`.`fileingestjobmetadata`, CONSTRAINT `fileingestjobmetadata_ibfk_3` FOREIGN KEY (`fileIngest`) REFERENCES `FileIngest` (`id`))
```

**Comment by tommydeboer** [comment]
Is it possible to refresh the import job table after you click 'Execute now'  so you can immediately see the new job?

**Comment by erwinwinder** [comment]
You must delete the FileIngest jobs first. This is standard molgenis behaviour, no cascading deletes.

Import table refresh after 'Execute now' can be done but, but when the jobs actually runs is up to the scheduler, so no guarantee that job is already created.

**Comment by tommydeboer** [comment]
Ok I see. Maybe we should add a 'delete all' button in the future so you don't have to manually remove all the jobs (which could be hundreds).

**Comment by erwinwinder** [comment]
You can delete all jobs in the dataexplorer

**Comment by tommydeboer** [comment]
We have the request that you do a separate pull request for the fix for issue #4424 so we can test it separately.

**Comment by tommydeboer** [comment]
>You can delete all jobs in the dataexplorer
Wouldn't that also delete all jobs of other automatic imports?

**Comment by erwinwinder** [comment]
Implemented refresh after 'execute now'

**Comment by fdlk** [comment]
I merged with master, opening pull request from my repo.

**Pull request closed without merging**
