### PR TITLE
Fix #7379 EMX import package assignment

### LINKED ISSUE #7379: Import wizard package assignment broken
### How to Reproduce
- As superuser import [it_emx_autoid_no_packages.xlsx](https://github.com/molgenis/molgenis/files/2038681/it_emx_autoid_no_packages.xlsx) using the 'Advanced data import' plugin. In step 3 select package ```it_emx```.

### Expected behavior
- Entity type ```testAutoId``` is imported in package ```it > emx```

### Observed behavior
- Entity type ```testAutoId``` is imported in package ```base```

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by fdlk** [comment]
Unit tests are failing.

**Comment by dennishendriksen** [comment]
> Unit tests are failing.
GavinAnnotatorTest. this is very strange ...

**Comment by dennishendriksen** [comment]
Discussed with @bartcharbon and @mswertz: we'll remove the Gavin annotator since its not used anymore.

**Comment by dennishendriksen** [comment]
Fix has unexpected side effects, back to the drawingboard ...

**Pull request closed without merging**
