### PR TITLE
Fix #6800 Not able to enter multiple email addresses for scheduled jobs

### LINKED ISSUE #6800: Not able to enter multiple email addresses for scheduled jobs
### How to Reproduce

Enter a comma separated list of email addresses in the succes email or failure email field.

### Expected behavior

I can enter multiple email addresses, comma separated.
This is actually what the description of the field tells me: "Comma-separated list of emails. Leave blank if you don't want to receive emails if the jobs failed."

### Observed behavior

Only one email can be given. It gives an error message : "please enter a valid email address."

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
change field type to String, the code processing the mail list expects a comma separated string

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

**Comment by fdlk** [comment]
I want my generic value list type!

**Comment by ConnorStroomberg** [comment]
@fdlk be careful what you wish for :)

But yes that would be nice, maybe ( maybe not). This PR fixes the issue for the user, the same data type String is used for other fields and the code handeling the data seems to expect a comma separated string list. The  'generic value list type' is a high impact story that is not 'ready to plan'.

**Comment by Mark-de-Haan** [comment]
Breaking change: Can not alter system entity metadata, so drop your database!

**Comment by fdlk** [comment]
@Mark-de-Haan We already have one of those for the null expressions so keep 'em coming! :)

**Comment by dennishendriksen** [comment]
@ConnorStroomberg the single email address was validated, the multiple email addresses are not (typical use case, my value is 'you@molgenis.org;me@molgenis.org').

Validation can be restored by using a validation expression or better by introducing an entity type decorator for scheduled job that reuses existing email address validation code.

**Pull request merged**
