### PR TITLE
M4939 Importer integration tests

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

**Comment by ConnorStroomberg** [comment]
test this please

**Comment by ConnorStroomberg** [comment]
test this please

**Comment by ConnorStroomberg** [comment]
@tommydeboer i updated the emxImport test en processed the 'fixme' tags, but two tests still fail ( see jenkins) could you take a look at these ? , I'm am not sure the assertions are correct.

**Comment by ConnorStroomberg** [comment]
test this please

**Comment by ConnorStroomberg** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Pull request merged**
