### PR TITLE
Fix #3181 Field type IMAGE not implemented

### LINKED ISSUE #3181: Field type IMAGE not implemented
MOLGENIS defines a field type IMAGE in MolgenisFieldTypes.java but is not implemented. Either remove the field type from MOLGENIS or implement it similar to the FILE data type.

### PR DESCRIPTION
**Pull request by Mark-de-Haan**

### CODE REVIEW

**Comment by dennishendriksen** [comment]
Remove the corresponding FieldTypeEnum.IMAGE as well as 26 other locations in Java, JavaScript and Freemarker referring to this image type.

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Pull request merged**
