### PR TITLE
Feature/ngram tagging

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

**Comment by jjettenn** [comment]
Je zal willen pullen van de master..

**Comment by Mark-de-Haan** [comment]
bump to get this up to date

**Comment by fdlk** [comment]
It's not in the current sprint, I think?

**Comment by Mark-de-Haan** [comment]
It was made and is out of date. Should be in the master or not? Else close pull request

**Comment by fdlk** [comment]
It should be merged with the master once we get back to the automatic tagging.

**Comment by Mark-de-Haan** [comment]
Closing pull request until we get back to that then.

**Pull request closed without merging**
