### PR TITLE
[GF] Java 9

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by mark-de-haan** [comment]
Can we close this? Or is it something we actually want?

**Comment by fdlk** [comment]
I'd split into two stories: compile and run with java 9 and make modular using jigsaw

**Comment by ConnorStroomberg** [comment]
@fdlk @dennishendriksen Can this be closed ?, and implement [As dev I want to migrate to Java 11 to increase productivity]( http://wiki.gcc.rug.nl/ticket/5739)

**Comment by tommydeboer** [comment]
Happy belated anniversary! :tada:

**Pull request closed without merging**
