### PR TITLE
Fix #5573 Elasticsearch document type and field name identifiers

### LINKED ISSUE #5573: Sort Data type results in error
#### Reproduce
- Import [emx_all_datatypes.xlsx](https://github.com/molgenis/molgenis/files/591236/emx_all_datatypes.xlsx) in ADD mode
- Go to data explorer and select Attribute entity.
- Search for xbool and change datatype to string. 
- Sort Data type

#### Expected
Data type is sorted

#### Observed
Error! Failed to execute phase [query], all shards failed; shardFailures {[Q32gpkcGTrK7fIF2swhC2g][molgenis][0]: SearchParseException[[molgenis][0]: query[_all:typetest],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"match":{"_all":{"query":"TypeTest","type":"phrase","slop":10}}},"sort":[{"type.raw":{"order":"asc","mode":"min"}}]}]]]; nested: QueryParsingException[[molgenis] [nested] failed to find nested object under path [type]]; }

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Unit tests

### CODE REVIEW

**Comment by bartcharbon** [comment]
The aggregates show "No results found" for xbool vs xboolnillable. On m62 (2.0.0) there is a result for those attributes.

**Comment by bartcharbon** [comment]
The mapping service does not auto generate any mappings for typetest on typetest. On m62 almost all mappings are generated.

**Comment by bartcharbon** [comment]
Aggregates are showing again, but they error on xbool x xmref_value "Error! Missing terms aggregation". Same query does work on m62

**Comment by dennishendriksen** [comment]
test this please

**Pull request merged**
