### PR TITLE
[CHORE] Add frontend module, remove frontend sources

### PR DESCRIPTION
**Pull request by fdlk**
# what
* Moves the `*/src/main/frontend` code to the https://github.com/molgenis/molgenis-frontend repository.
* Adds `molgenis-frontend` module that downloads the frontend modules from npm and puts their contents in a molgenis-frontend jarfile.
* If you want to see the diff without the ton-of-removed-files, you can check a box at the bottom of the file filter in the "files changed" tab

# how
## this PR
* Remove the sources in `*/src/main/frontend`
* Remove a couple of library files in core-ui that get used in the react build
* Remove source file for bootstrap 4 molgenis blue theme in core-ui that gets used in the theme build
* Remove frontend-maven plugin from maven poms
* Remove skip-js profile from maven poms

## molgenis-frontend repository
* Adds the sources from commit 83d0fc95f3d2efad653d54b4e89364c4cca78aa7 to the molgenis-frontend repository using [a script](https://github.com/molgenis/molgenis-frontend/blob/4ba54bb/build.xml).
* Adapt the package.jsons to build to work dir's dist directories
* Add version management for the modules
* Add jenkinsfile that builds, tests and publishes the npm modules
### core-ui
* Add `lib` dir and publish the library files to npm
* Add source file for bootstrap 4 molgenis blue theme and publish the css to npm
 
# why
## reduces clutter
* The frontend repository gives a better overview of what javascript plugins we have
* Use javascript build tool for javascript and java build tool for java
* Cleaner logging and reporting on both sides
## reduces build time
A `mvn clean install -DskipTests -T4` of molgenis/molgenis repo is reduced to about 1m45s
A run of the molgenis pull request job on jenkins is reduced to about 13m, build plus tests taking 8m
The duration of travis PR builds is reduced from 21m to 11m
## reproducability
No need to skip js compilation which uses whatever it finds on your harddisk. The javscript artifacts are reproducibly downloaded from the registry by the molgenis-frontend module
## stability
* The maven build no longer needs to download and execute yarn so no more hiccups caused by failed download of yarn [like in this build](https://jenkins.dev.molgenis.org/job/molgenis/job/molgenis/view/change-requests/job/PR-8205/1/console):
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) on project molgenis-menu: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.13.0/yarn-v1.13.0.tar.gz: Unknown host github-production-release-asset-2e65be.s3.amazonaws.com: Temporary failure in name resolution -> [Help 1]

and in [this build](https://jenkins.dev.molgenis.org/blue/organizations/jenkins/molgenis%2Fmolgenis/detail/PR-8218/3/pipeline)
> [ERROR] ChromeDriver installation failed Error with http(s) request: Error: connect ETIMEDOUT 172.217.20.80:443

And no more hiccups and warnings caused by concurrent runs of yarn install.
## cleaner split between controller and frontend
* The javascript module's package.json no longer refers to maven's `../../../target/classes`
* Independent versioning

# why not?
* Version management is hard
* Lerna is a new tool and we'll have to get used to its quirks
* Copy loses git history

## mixed blessings
* The download from npm is simple and fast but no longer allows us to use yarn features like semantic versioning in the maven build.
* Certain feature implementations with big controller api changes will end up in two PRs to two repositories.
* Separate version management is a deliberate choice and makes it clearer what got changed when but it does mean that the frontend module now needs to list the specific versions of dependencies to include.
* Different developer workflow

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- Code unit/integration/system tested
- [x] User documentation updated (check molgenis/molgenis-frontend)
- (If you have changed REST API interface) view-swagger.ftl updated
- Test plan template updated
- [x] Clean commits
- Added Feature/Fix to release notes

### CODE REVIEW

**Comment by fdlk** [comment]
@sidohaakma 
> Can you build MOLGENIS without having to do anything with molgenis-frontend? So does it pull the NPM packages from the registry always. Ideally I only want to checkout molgenis-frontend when I am developing new features or bug fixes in the frontend module.

Yes, that's how it works. The molgenis-frontend module downloads released artifacts and puts them in a jar.

> what does this mean: The download from npm is simple and fast but no longer allows us to use yarn features like semantic versioning in the maven build.

No package.json in the molgenis-frontend module of the molgenis/molgenis repo, just a list of npm packages to include. Benefit is that we get rid of the overhead of running yarn, but this also means that you need to specify explicit version numbers, down to the last comma, maven style. And that you do not get the yarn cache and lockfile and stuff.

**Comment by tommydeboer** [comment]
I wonder how @dennishendriksen and @bartcharbon will feel after seeing those remove stats 😄

**Comment by fdlk** [comment]
Fixes #8129

**Comment by fdlk** [comment]
Update: We've switched back to using the maven frontend plugin in the frontend module to download and unpack the frontend modules from the npm registry. This takes a bit longer and is a bit heavier on the tool side but it allows you to depend on semantic versions and tags in the package.json. This makes consecutive updates to a module less laborous because the latest version will get picked up at build time.

**Pull request merged**
