### PR TITLE
M4016: Job metadata

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by bartcharbon** [comment]
We need some extension system to store additional information depending on the specific job. for example: the annotators need to store which entity is being annotated.

**Pull request merged**
