### PR TITLE
Performance: ACL class caching

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes
- [ ] Integration tests run correctly

### CODE REVIEW

**Comment by fdlk** [comment]
Sunday's test run of master branch failed with same error(!)
See https://travis-ci.org/molgenis/molgenis/builds/363782968?utm_source=slack&utm_medium=notification

**Comment by fdlk** [comment]
@dennishendriksen Can you add unit test?

**Comment by dennishendriksen** [comment]
@fdlk Unit tests already exist for updated methods. Which unit test cases are you missing?

**Comment by fdlk** [comment]
@dennishendriksen I thought one assert that two calls cause only one load

**Comment by dennishendriksen** [comment]
test this please

**Comment by fdlk** [comment]
Figured out what's the matter: the cache doesn't get invalidated upon AclClass creation (and therefore keeps returning `false` even when the answer has become `true`.
Found a second issue: transaction rollback doesn't invalidate the AclClass cache.

**Comment by fdlk** [comment]
Closing for #7305, am not allowed to push to repo.

**Pull request closed without merging**
