### PR TITLE
[1.9] M3504 Add VCF validation step to VCF writing functions

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
FAILED: gonl
java.io.FileNotFoundException: File 'target/out-gonl-test.vcf' does not exist

Tests still fail :(

**Comment by fdlk** [comment]
That test is broken in 1.9, we broke it when I accepted your pull request #3648 . Gonl annotator no longer works in 1.9.

**Comment by Mark-de-Haan** [comment]
Then we remove @test annotation from gonl and accept?

**Comment by bartcharbon** [comment]
Why does this need to be added to 1.9? This is functionality right? not a bugfix.

**Comment by Mark-de-Haan** [comment]
Reasoning was that; we want to make 1.9 cmdline annotators usable for analysis team. This feature makes the cmdline annotators 10x more user friendly, and less prone to bugs because of proper argument parsing

**Pull request closed without merging**
