### PR TITLE
[master] Fix #4098 GoNL annotator writes out INFO field with '.' when no results are found

### LINKED ISSUE #4098: GoNL annotator writes out INFO field with '.' when no results are found
When no results are found within GoNL, the INFO fields should remain untouched. However, 'null' strings are written out as such:

```
AC=1;AF=0.5;AN=2;set=variant38;GoNL_GTC=.,.,.;GoNL_AF=.;
```
This should be:

```
AC=1;AF=0.5;AN=2;set=variant38;
```

### PR DESCRIPTION
**Pull request by tommydeboer**

### CODE REVIEW

**Comment by tommydeboer** [comment]
Test this please

**Comment by tommydeboer** [comment]
retest this please

**Comment by tommydeboer** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Pull request merged**
