### PR TITLE
Fix #5357 add and delete attribute

### LINKED ISSUE #5357: Added attributes are not persisted to the database
#### Reproduce

Run l3Cache IT 
or
Adding an attribute in the UI
#### Expected

Runs
#### Observed

Nullpointer
The added attribute date_attr is not found when calling the findOneById method in the RepositoryValidationDecorator

### PR DESCRIPTION
**Pull request by jjettenn**
#### Checklist
- [ ] Unit tests
- [ ] Updated testplan

### CODE REVIEW

**Comment by jjettenn** [comment]
test this please

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Are you reviewing this pull request? You added comments without assigning yourself to this PR.

**Comment by jjettenn** [comment]
test this please

**Comment by jjettenn** [comment]
test this please

**Comment by fdlk** [comment]
Cannot get this right for both entity insert/delete and attribute stream insert/delete if we do not coordinate the changes better. Closing for now.

**Pull request closed without merging**
