### PR TITLE
Fix #5674 DATE and DATE_TIME persisted with too much detail in PostgreSQL

### LINKED ISSUE #5674: DATE and DATE_TIME persisted with too much detail in PostgreSQL
### How to Reproduce
1. Open data explorer, Token entity
2. Select a row to edit
3. Save without changing value
4. Save

### Expected behavior
Is saved

### Observed behavior
Error! The attribute 'creationDate' of entity 'sys_sec_Token' can not be changed it is readonly. (entity 1)

### PR DESCRIPTION
**Pull request by jjettenn**
#### Checklist
- [ ] Unit tests
- [ ] Updated testplan

### CODE REVIEW

**Comment by jjettenn** [comment]
test me please

**Comment by jjettenn** [comment]
test this please

**Comment by fdlk** [comment]
Couple remarks about this:

* If this change only aims to reduce the precision stored to seconds, then wouldn't it be better to do so in the table definition by specifying the column datatype as TIMESTAMP(0)?
* It's very inefficient to create a new SimpleDateFormatter for each time-valued cell we store
* Fiddling with Europe/Amsterdam timezone is a bit imperialistic. But worse, it means that the values will not be continuous around moments when daylight savings time starts or ends. Just wait for the index job that lasted -3600 seconds.
* Wouldn't molgenis compute type users actually enjoy millisecond precision?

**Comment by dennishendriksen** [comment]
@fdlk Good remarks that we should definitely discuss. can you create a story in the backlog? Else your remarks might never be addressed.
@fdlk Do you think we should revert the fix?

**Comment by fdlk** [comment]
@dennishendriksen I've created http://www.molgenis.org/ticket/4691 and no, let's not revert this.

**Pull request merged**
