### PR TITLE
Fix #5909 Entity type specific repository decoration differences

### LINKED ISSUE #5909: Entity type specific repository decoration differences
### How to Reproduce
- Inspect [MolgenisRepositoryDecoratorFactory.java](https://github.com/molgenis/molgenis/blob/de529a9715fb34d2ded9939a988074a202abd106/molgenis-data-platform/src/main/java/org/molgenis/data/platform/decorators/MolgenisRepositoryDecoratorFactory.java#L138)

### Expected behavior
- Entity type specific repository decorators are applied at the same position in the decoration chain

### Observed behavior
- Repository decorators registered in the repository decorator registry are applied at position 13
- Repository decorators for entities User, Attribute, Entity type, Package, Tag, Language, I18n and Mail settings are applied at position 7

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by ConnorStroomberg** [comment]
Failing tests need to have config fixed: 

ImportWizardControllerTest.springTestContextPrepareTestInstance	
MappingProjectRepositoryImplTest.springTestContextPrepareTestInstance
FileIngesterQuartzJobTest.springTestContextPrepareTestInstance

**Comment by ConnorStroomberg** [comment]
FileIngesterJobSchedulerTest and EntityMappingRepositoryImplTest need the same fix

**Comment by dennishendriksen** [comment]
Depends on #5933

**Comment by dennishendriksen** [comment]
test this please

**Comment by dennishendriksen** [comment]
test this please

**Comment by dennishendriksen** [comment]
test this please

**Comment by dennishendriksen** [comment]
test this please

**Comment by dennishendriksen** [comment]
test this please

**Pull request closed without merging**
