### PR TITLE
fix: added nonnull annotation to EntityMapper

### PR DESCRIPTION
**Pull request by sidohaakma**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- Code unit/integration/system tested
-  Migration step added in case of breaking change
-  User documentation updated
-  (If you have changed REST API interface) view-swagger.ftl updated
-  Test plan template updated
- [x] Clean commits
-  Added Feature/Fix to release notes

### CODE REVIEW

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Comment by sidohaakma** [comment]
[Investigate rowMapper to not throw an entity which is null](https://trello.com/c/t6ODSu3D/491-investigate-rowmapper-to-not-throw-an-entity-which-is-null)

**Review by tommydeboer — APPROVED** [review]

**Pull request merged**
