### PR TITLE
Fix attribute label and lookup validation bugs

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits (will be squashed on merge)
- [x] Added Feature/Fix to release notes
- [x] Integration tests run correctly

### CODE REVIEW

**Comment by dennishendriksen** [comment]
- Import [it_emx_autoid.xlsx](https://github.com/molgenis/molgenis/files/1862833/it_emx_autoid.xlsx)
- Update the id attribute visible --> non-visible using the metadata manager
Result: label attribute now refers to an invisible attribute

**Comment by fdlk** [comment]
Discussed at SOS: this fixes the bugs, leftover issues to be addressed later.

**Comment by tommydeboer** [comment]
@dennishendriksen @fdlk Have the leftovers been recorded as GitHub issues?

**Comment by dennishendriksen** [comment]
@tommydeboer no

**Comment by tommydeboer** [comment]
@dennishendriksen Your findings have been fixed in #7395

**Pull request merged**
