### PR TITLE
Fix #4504 Deleting entities isn't logged

### LINKED ISSUE #4504: Deleting entities isn't logged
When a dataset is deleted by a (super)user it isn't logged. The admin can't track if it was deleted by somebody or not.

### PR DESCRIPTION
**Pull request by tommydeboer**

### CODE REVIEW

**Comment by fdlk** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Comment by bartcharbon** [comment]
I'd propose to add the user to the message

**Comment by tommydeboer** [comment]
test this please

**Pull request merged**
