### PR TITLE
[1.17] Fix #4491 No READ permission on AnnotationJobMetaData when starting my App with a clean database

### LINKED ISSUE #4491: No READ permission on AnnotationJobMetaData when starting my App with a clean database
The `@RunAsSystem` Spring annotation on the `onApplicationEvent` method in the `AnnotationServiceImpl` class does not seem to be working.

### PR DESCRIPTION
**Pull request by Mark-de-Haan**

### CODE REVIEW

**Comment by bartcharbon** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
@bartcharbon these PR do not have your null check fix yet. I couldnt cherry-pick off the master so I created the same fix for the 1.17 branch. Although this will probably end in merge conflicts...

**Comment by bartcharbon** [comment]
it appears there is another already merged request in this one...

**Comment by tommydeboer** [comment]
test this please

**Pull request merged**
