### PR TITLE
M5385: Security Story 1: Create User, Group, Role (WIP)

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

**Comment by dennishendriksen** [comment]
@fdlk PR says WIP: add work-in-progress label? What needs to change in order to be able to merge this PR?

**Comment by fdlk** [comment]
@dennishendriksen A review. There's a story for finishing this, but it's not in our sprint.

**Comment by dennishendriksen** [comment]
@fdlk Could you add a Todo section in the PR description containing the story link?

**Comment by fdlk** [comment]
Closing till we get back to this.

**Pull request closed without merging**
