### PR TITLE
Update node to 8.9.0 (new  LTS version)

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
Update node to 8.9.0 (new LTS version), should improve build times.

! Developers should be notified on merge to update the local node version to 8.9.0

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [ ] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
In every `package.json` file we declare:
```
"engines": {
    "node": ">= 6.11.0",
    "yarn": ">= 0.24.5"
  }
```
Do we want to increase this version to 8.0?

`check-versions.js` uses this to mercilessly bash the user if their local node version is not up to date

**Comment by ConnorStroomberg** [comment]
@Mark-de-Haan yes good point , i suggest we change it to >= 8.9.0 . I test and update the PR

**Comment by Mark-de-Haan** [comment]
And I forgot, in the docs/developer_documentation/frontend-development.md we mention on the 4th line which Node version we use

**Comment by Mark-de-Haan** [comment]
And we should start making a list of stuff to change in the MOLGENIS vue template

**Pull request merged**
