### PR TITLE
Fix #6609 Advanced importer does not show entity fields

### LINKED ISSUE #6609: Advanced importer does not show entity fields
Seen and reproduced on molgenis01 where 5.2.0-SNAPSHOT is deployed. A valid EMX file is put in the advanced importer, and after going through the steps the import does success as expected.

However, in screen 4 (Validation), there are no entity fields shown. Here, it should have shown a number of fields about to be imported. See screenshot.

screen shot 2017-09-08 at 8 57 24 am

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by bartcharbon** [comment]
Seems to have killed the functionality when the entities are already in a package... will need to improve the fix

**Comment by Mark-de-Haan** [comment]
Importing the VCF file inside [example.zip](https://github.com/molgenis/molgenis/files/1374950/example.zip) will work on current master, but fails with `null id` on this branch

**Comment by bartcharbon** [comment]
Found the problem, no clue how it is related to this PR though

**Comment by Mark-de-Haan** [comment]
VcfImporterServiceTest.java is failing atm

**Pull request merged**
