### PR TITLE
As a MOLGENIS developer I want to reach Reliability Rating C

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- (na) Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by tommydeboer** [comment]
test this please

**Comment by dennishendriksen** [comment]
Default build failed due to:
```
RROR: Aborted Maven execution for InterruptedIOException
java.net.SocketTimeoutException: Accept timed out
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at hudson.maven.AbstractMavenProcessFactory$SocketHandler$AcceptorImpl.accept(AbstractMavenProcessFactory.java:213)
	at hudson.maven.AbstractMavenProcessFactory.newProcess(AbstractMavenProcessFactory.java:282)
	at hudson.maven.ProcessCache.get(ProcessCache.java:236)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

**Comment by dennishendriksen** [comment]
test this please

**Comment by dennishendriksen** [comment]
Default build fails with:
```
Error Message
Wanted but not invoked:
cellProcessor.process("val1");
-> at org.molgenis.data.csv.CsvRepositoryTest.addCellProcessor_data(CsvRepositoryTest.java:108)
Actually, there were zero interactions with this mock.
Stacktrace
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
cellProcessor.process("val1");
-> at org.molgenis.data.csv.CsvRepositoryTest.addCellProcessor_data(CsvRepositoryTest.java:108)
Actually, there were zero interactions with this mock.

	at org.molgenis.data.csv.CsvRepositoryTest.addCellProcessor_data(CsvRepositoryTest.java:108)
```

**Pull request merged**
