### PR TITLE
M4755 As BBMRI-ERIC I want to send my selection to negotiator

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
Test this please

**Comment by fdlk** [comment]
I've fixed some simple things. Only have one bug left: When I edit the filter by adding "size>10", the resulting human readable form forgets the other mref human readable things.

**Comment by fdlk** [comment]
Hey @Mark-de-Haan , how can I give permissions on directory controller?

**Pull request merged**
