### PR TITLE
Fix #3536 AbstractEntity toString does not print the compound

### LINKED ISSUE #3536: AbstractEntity toString does not print the compound
The AbstractEntity toString method prints "attributename=null" for the compounds, instead of the values of the attributes inside the compound.

This is not ideal for for example unit tests. (results in different "actual" than "expected" values, where the IDE will show you to identical Strings)

### PR DESCRIPTION
**Pull request by dennishendriksen**

### CODE REVIEW

**Comment by fdlk** [comment]
I get NPE when I run the tests for molgenis-data-jpa

**Comment by dennishendriksen** [comment]
Cannot reproduce:
Tests run: 49, Failures: 0, Errors: 0, Skipped: 0
[INFO] BUILD SUCCESS

**Comment by fdlk** [comment]
Happens when I checkout the master, merge pull request, and build:

```
Fleurs-MacBook-Pro:molgenis fkelpin$ git status
On branch master
Your branch is up-to-date with 'blessed/master'.
nothing to commit, working directory clean
Fleurs-MacBook-Pro:molgenis fkelpin$ git fetch blessed master
From https://github.com/molgenis/molgenis
 * branch            master     -> FETCH_HEAD
Fleurs-MacBook-Pro:molgenis fkelpin$ git checkout -b test/3536
Switched to a new branch 'test/3536'
Fleurs-MacBook-Pro:molgenis fkelpin$ git pull dennis fix/3536
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 34 (delta 11), reused 30 (delta 7), pack-reused 0
Unpacking objects: 100% (34/34), done.
From https://github.com/dennishendriksen/molgenis
 * branch            fix/3536   -> FETCH_HEAD
   a6c61be..dbe4cdc  fix/3536   -> dennis/fix/3536
Merge made by the 'recursive' strategy.
 molgenis-data/src/main/java/org/molgenis/data/support/AbstractEntity.java     | 29 ++++++++++++++++++++---------
 molgenis-data/src/test/java/org/molgenis/data/support/AbstractEntityTest.java | 70 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 90 insertions(+), 9 deletions(-)
 [...]
 Tests run: 49, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 14.812 sec <<< FAILURE! - in TestSuite
testMref(org.molgenis.data.jpa.JpaImportTest)  Time elapsed: 0.275 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:394)
	at org.molgenis.data.jpa.importer.EntityImportService.importEntity(EntityImportService.java:155)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:57)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:38)
	at org.molgenis.data.jpa.JpaImportTest.testMref(JpaImportTest.java:133)

testMrefWrong(org.molgenis.data.jpa.JpaImportTest)  Time elapsed: 0.194 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:394)
	at org.molgenis.data.jpa.importer.EntityImportService.importEntity(EntityImportService.java:155)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:57)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:38)
	at org.molgenis.data.jpa.JpaImportTest.testMrefWrong(JpaImportTest.java:154)

testOk(org.molgenis.data.jpa.JpaImportTest)  Time elapsed: 0.133 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:394)
	at org.molgenis.data.jpa.importer.EntityImportService.importEntity(EntityImportService.java:155)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:57)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:38)
	at org.molgenis.data.jpa.JpaImportTest.testOk(JpaImportTest.java:63)

testXref(org.molgenis.data.jpa.JpaImportTest)  Time elapsed: 0.166 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:394)
	at org.molgenis.data.jpa.importer.EntityImportService.importEntity(EntityImportService.java:155)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:57)
	at org.molgenis.data.jpa.importer.AbstractEntitiesImporter.importEntities(AbstractEntitiesImporter.java:38)
	at org.molgenis.data.jpa.JpaImportTest.testXref(JpaImportTest.java:101)

testImportAdd(org.molgenis.data.jpa.JpaRepositoryTest)  Time elapsed: 0.108 sec  <<< FAILURE!
org.testng.TestException:
Expected exception org.molgenis.data.MolgenisDataException but got java.lang.NullPointerException
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:375)
	at org.molgenis.data.jpa.JpaRepositoryTest.testImportAdd(JpaRepositoryTest.java:233)

testImportAddUpdateExisting(org.molgenis.data.jpa.JpaRepositoryTest)  Time elapsed: 0.104 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:113)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:394)
	at org.molgenis.data.jpa.JpaRepositoryTest.testImportAddUpdateExisting(JpaRepositoryTest.java:251)

testImportUpdate(org.molgenis.data.jpa.JpaRepositoryTest)  Time elapsed: 0.108 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.JpaRepository.add(JpaRepository.java:98)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:67)
	at org.molgenis.data.jpa.JpaRepositoryTest.testImportUpdate(JpaRepositoryTest.java:280)

testImportUpdateMissing(org.molgenis.data.jpa.JpaRepositoryTest)  Time elapsed: 0.002 sec  <<< FAILURE!
org.testng.TestException:
Expected exception org.molgenis.data.MolgenisDataException but got java.lang.NullPointerException
	at org.molgenis.data.support.AbstractEntity.toString(AbstractEntity.java:164)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.molgenis.data.jpa.importer.EntityImportService.update(EntityImportService.java:407)
	at org.molgenis.data.jpa.JpaRepositoryTest.testImportUpdateMissing(JpaRepositoryTest.java:271)


Results :

Failed tests:
  JpaImportTest.testMref:133 » NullPointer
  JpaImportTest.testMrefWrong:154 » NullPointer
  JpaImportTest.testOk:63 » NullPointer
  JpaImportTest.testXref:101 » NullPointer
  JpaRepositoryTest.testImportAdd » Test
Expected exception org.molgenis.data.M...
  JpaRepositoryTest.testImportAddUpdateExisting:251 » NullPointer
  JpaRepositoryTest.testImportUpdate:280 » NullPointer
  JpaRepositoryTest.testImportUpdateMissing » Test
Expected exception org.molge...

Tests run: 49, Failures: 8, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Molgenis ........................................... SUCCESS [  1.772 s]
[INFO] molgenis-core ...................................... SUCCESS [  9.890 s]
[INFO] molgenis-security-core ............................. SUCCESS [  3.174 s]
[INFO] molgenis-data ...................................... SUCCESS [  9.591 s]
[INFO] molgenis-data-csv .................................. SUCCESS [  2.588 s]
[INFO] molgenis-data-elasticsearch ........................ SUCCESS [ 13.124 s]
[INFO] molgenis-file ...................................... SUCCESS [  1.649 s]
[INFO] molgenis-scripts-core .............................. SUCCESS [  2.546 s]
[INFO] molgenis-js ........................................ SUCCESS [ 21.858 s]
[INFO] molgenis-data-validation ........................... SUCCESS [  3.106 s]
[INFO] molgenis-data-excel ................................ SUCCESS [  4.373 s]
[INFO] molgenis-data-jpa .................................. FAILURE [ 16.177 s]
[INFO] molgenis-security .................................. SKIPPED
[INFO] molgenis-data-system ............................... SKIPPED
[INFO] molgenis-core-ui ................................... SKIPPED
[INFO] molgenis-data-rest ................................. SKIPPED
[INFO] molgenis-data-merge ................................ SKIPPED
[INFO] molgenis-data-vcf .................................. SKIPPED
[INFO] molgenis-data-annotators ........................... SKIPPED
[INFO] molgenis-dataexplorer .............................. SKIPPED
[INFO] molgenis-ontology-core ............................. SKIPPED
[INFO] molgenis-data-mysql ................................ SKIPPED
[INFO] molgenis-data-semanticsearch ....................... SKIPPED
[INFO] molgenis-data-import ............................... SKIPPED
[INFO] molgenis-r ......................................... SKIPPED
[INFO] molgenis-ontology .................................. SKIPPED
[INFO] molgenis-das ....................................... SKIPPED
[INFO] molgenis-pathways .................................. SKIPPED
[INFO] molgenis-disease-matcher ........................... SKIPPED
[INFO] molgenis-data-googlespreadsheet .................... SKIPPED
[INFO] molgenis-python .................................... SKIPPED
[INFO] molgenis-charts .................................... SKIPPED
[INFO] molgenis-data-mapper ............................... SKIPPED
[INFO] molgenis-model-registry ............................ SKIPPED
[INFO] molgenis-data-migrate .............................. SKIPPED
[INFO] molgenis-questionnaires ............................ SKIPPED
[INFO] molgenis-catalogue ................................. SKIPPED
[INFO] molgenis-scripts ................................... SKIPPED
[INFO] molgenis-app ....................................... SKIPPED
[INFO] molgenis-data-examples ............................. SKIPPED
[INFO] molgenis-data-rest-client .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:30 min
[INFO] Finished at: 2015-09-07T11:25:54+02:00
[INFO] Final Memory: 72M/416M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project molgenis-data-jpa: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/fkelpin/git/molgenis/molgenis-data-jpa/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :molgenis-data-jpa
```

**Comment by dennishendriksen** [comment]
Fix for entities that don't have entity meta data.

**Pull request merged**
