### PR TITLE
Fix #5230: QueryRule equals + integration test method for caching performance measurement

### LINKED ISSUE #5230: QueryRule equals method too strict
#### Reproduce
Compare two identical QueryRule instances, but with Entity value set to two instances of an entity with the same idValue.

#### Expected
equals() returns true

#### Observed
equals() returns false

This causes unnecessary misses in the L3 / query cache.

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [x] Unit tests
- [ ] Updated testplan

### CODE REVIEW

**Comment by bartcharbon** [comment]
integration test: testFindQueryOperatorRange[10,10,[0]] fails

**Comment by fdlk** [comment]
For the range operator, storing the values in a set is not particularly wise :)

**Comment by fdlk** [comment]
Test this please

**Comment by fdlk** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Pull request merged**
