### PR TITLE
[feature/3494] M3494 Create molgenis-react project for the react components.

### PR DESCRIPTION
**Pull request by fdlk**
Build using npm plugin.
Add simple jest test.
Add the generated js file to the header.

### CODE REVIEW

**Comment by Mark-de-Haan** [comment]
Ohh it seems we need maven version 3.1.0 to use the front-end maven plugin

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by fdlk** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by Mark-de-Haan** [comment]
Could you merge with master again? Then I will accept it into the feature branch so we can close this PR

**Pull request merged**
