### PR TITLE
Feature/js modular

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

**Comment by fdlk** [comment]
Jenkins: Test this please

**Comment by fdlk** [comment]
Jenkins: Test this please

**Comment by Mark-de-Haan** [comment]
In the data explorer, try to edit a row for the TypeTest entity:
screen shot 2016-01-20 at 17 26 37

**Comment by Mark-de-Haan** [comment]
When clicking an xref in the dataexplorer using TypeTest entity:
screen shot 2016-01-20 at 17 33 48

**Pull request closed without merging**
