### PR TITLE
Fix #4713: AUTO id columns overwrite specified id value

### LINKED ISSUE #4713: AUTO id columns overwrite specified id value
If you specify an ID value for an AUTO id column, the value gets overwritten when you call dataservice.add().

I'd expect the AUTO id only to work when you specify NULL as a value.

### PR DESCRIPTION
**Pull request by fdlk**

### CODE REVIEW

**Comment by dennishendriksen** [comment]
What is the desired behavior here?
1) Auto id column do not overwrite id value
2) Auto id column do not overwrite id value, exception is thrown
3) Auto id column overwrites id value

I would expect 3) or alternatively 2) since this is probably a user error. Furthermore some validation steps are not executed for auto id columns, since we know that the system generates them.

**Comment by fdlk** [comment]
Sorta job execution entity extends the abstract JobExecution which has auto ID.
BUT for the sorta job execution entity it happens to be pretty handy to be able to specify the ID before adding the entity to the repo.
So there we'd like to generate one of our own and would desire behavior nr 1 please!

**Comment by dennishendriksen** [comment]
In case of 1) AUTO attributes need to be validated.

**Comment by fdlk** [comment]
In particular uniqueness?

**Comment by fdlk** [comment]
I can also change the way I solved it in sorta, but a different use case where users will run into this is when you import entities with references through emx.

**Comment by dennishendriksen** [comment]
The same validation rules as when auto=false

**Comment by fdlk** [comment]
Only special validation that I can find is that null checks aren't executed for auto attributes. Presumably cause they'll be filled in by the autoValue decorator. That behavior remains correct so no changes needed there.

Also found that the streaming version of add() already does 1).

@dennishendriksen can you point out an example of such a special validation rule that I missed?

**Comment by dennishendriksen** [comment]
RepositoryValidationDecorator performs all entity validation, the corresponding test class contains about a hundred test cases that illustrate how entity validation works.

**Comment by dennishendriksen** [comment]
You can not reference to auto ids in EMX, in this case use your own ids.

**Comment by fdlk** [comment]
> Furthermore some validation steps are not executed for auto id columns, since we know that the system generates them.
I did not find a single case of that. Only that auto IDs don't get null checked. Which still is correct.

**Pull request merged**
