### PR TITLE
Make SORTA a superuser plugin by default

### PR DESCRIPTION
**Pull request by tommydeboer**
Documentation updated for this PR and #7593 

I also looked at the testplans:
 - Questionnaires (now uses the Editor role)
 - One-Click-Importer (already used the Manager role, no change needed) 
 - SORTA (wasn't updated to new group security yet. no change needed)

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by dennishendriksen** [comment]
Hoe about adding a `@PreAuthorize("hasAnyRole('ROLE_SU')")` on all mapped controller methods to enforce superuser-only usage?

**Comment by dennishendriksen** [comment]
@tommydeboer any clue why the coverage report looks like it does?

**Comment by tommydeboer** [comment]
@dennishendriksen 
> How about adding a @PreAuthorize("hasAnyRole('ROLE_SU')") on all mapped controller methods to enforce superuser-only usage?

That might be a bit too strict I think. At least now you can still configure it so that normal users can use SORTA, if you really want to.

**Comment by tommydeboer** [comment]
@dennishendriksen 
> any clue why the coverage report looks like it does?

No. The commit history is a bit messed up in this PR so I'll try cleaning that up first.

**Pull request merged**
