### PR TITLE
Refactor EntityMetaData to EntityType

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
#### Checklist
- [x] Unit tests
- [x] Updated testplan (not needed)

**Refactor:**
- EntityMetaDataMetaData to EntityTypeMetadata
- entityMetaMeta variable name to entityTypeMeta	
- EntityMetaDataFactory to EntityTypeFactory
- SystemEntityMetaData to SystemEntityType
- EntityMetaDataRepositoryFactory to EntityTypeRepositoryFactory	
- EntityMetaDataRepositoryValidationDecorator to EntityTypeRepositoryValidationDecorator
- EntityMetaDataResponse to EntityTypeResponse
- EntityMetaDataResponseV2 to EntityTypeResponseV2
- EntityMetaDataUtils to EntityTypeUtils
- EntityMetaDataValidator to EntityTypeValidator
EntityMetaData to EntityType

### CODE REVIEW

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Is the aggregatable --> isAggregatable change in the EMX format necessary?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Are any of these failures related to your changes?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] molgenis-data ...................................... FAILURE [ 43.831 s]
[INFO] molgenis-data-rest ................................. FAILURE [01:05 min]
[INFO] molgenis-data-annotators ........................... FAILURE [01:04 min]
[INFO] molgenis-annotators-cmd ............................ FAILURE [ 38.723 s]
[INFO] molgenis-platform-integration-tests ................ FAILURE [10:57 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by Mark-de-Haan** [comment]
@dennishendriksen 

No I don't think so,
My Branch compiles and clean install gives 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

Some tests are broken but that is because I havent merged with your one-to-many fixes yet

**Comment by dennishendriksen** [comment]
@Mark-de-Haan I'm currently working on merging with dennishendriksen/2.0_onetomany

**Comment by dennishendriksen** [comment]
@Mark-de-Haan I've completed the merge, see https://github.com/dennishendriksen/molgenis/tree/refactor/EntityMetadata. Tests are expected to succeed, but still fail.

**Comment by dennishendriksen** [comment]
See https://github.com/molgenis/molgenis/pull/5321

**Pull request closed without merging**
