### PR TITLE
M4215 As the Sorta developer, I would like to type the match results retrieved from the SortaServiceImpl

### PR DESCRIPTION
**Pull request by ChaoPang**

### CODE REVIEW

**Comment by fdlk** [comment]
Happy happy joy joy! Thanks for doing this!

**Comment by Mark-de-Haan** [comment]
test this please

**Comment by dennishendriksen** [comment]
@ChaoPang Can we postpone the merge until after the 2.0 release?

**Comment by dennishendriksen** [comment]
@ChaoPang Bump

**Comment by dennishendriksen** [comment]
No reply

**Pull request closed without merging**
