### PR TITLE
Fix #4510 If I copy my entity when annotating and the annotation fails, the created entity is not removed

### LINKED ISSUE #4510: If I copy my entity when annotating and the annotation fails, the created entity is not removed
## Reproduce
- Import the following file:
[test_no_samples_2.vcf.zip](https://github.com/molgenis/molgenis/files/132729/test_no_samples_2.vcf.zip)

- Annotate with SnpEff and check the create copy checkbox
- Annotation fails

## Expected
-  The copied entity is removed

## Observed
- The copied entity still exists, but contains 0 additional information

### PR DESCRIPTION
**Pull request by jjettenn**

### CODE REVIEW

**Comment by jjettenn** [comment]
test me please

**Comment by tommydeboer** [comment]
It is not possible to copy entities that are in the base package. The error is ```Error! Unknown entity [base_Test]``` but entities in the base package are not prefixed with that package name.

**Comment by jjettenn** [comment]
I have just copied an entity with package base (AnnotationJobExecution). Can you be more specific?

**Comment by tommydeboer** [comment]
I tried multiple entities including ```AnnotationJobExecution``` but I still get the error. I both tried checking out this branch (*fix/4510sprint82*) and by checking out the master and pulling from this branch. I did a clean install with dropped database and index.

**Pull request closed without merging**
