### PR TITLE
MySQL Repository stores VARCHAR as TEXT

### PR DESCRIPTION
**Pull request by tommydeboer**
The standard FieldType String is now stored as TEXT in the mysql backend, except for identifiers or foreign keys (xref/mref), which are still stored as VARCHAR.

### CODE REVIEW

**Comment by fdlk** [comment]
Will we make this configurable in molgenis-server.properties?

**Comment by mswertz** [comment]
yes

On Wed, Mar 25, 2015 at 10:37 AM, Fleur Kelpin <notifications@github.com>
wrote:

> Will we make this configurable in molgenis-server.properties?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/pull/2690#issuecomment-85956686>.
>



-- 
Morris A. Swertz
Associate Professor Big data in biomedicine
Coordinator BBMRI-NL common services for IT
Coordinator Health sector in DTL/ELIXIR-NL
Head Section Systems Genetics & Genomics Coordination Center
Dept of Genetics
University Medical Center Groningen
The Netherlands

**Comment by dennishendriksen** [comment]
Please add a migration script.

**Comment by tommydeboer** [comment]
Will first be added to meta-data-version branch.

**Pull request closed without merging**
