### PR TITLE
Make site generation compatible with java 8

### LINKED ISSUE #2290: Cobertura not working for Java 8 binaries
http://stackoverflow.com/questions/25627884/cobertura-maven-plugin-with-java-8
http://www.molgenis.org/jenkins/job/molgenis-reports/
Migrate to JaCoCo?

### PR DESCRIPTION
**Pull request by fdlk**
Use jacoco for code coverage and newer version of findbugs.

Fixes #2290

### CODE REVIEW

**Comment by dennishendriksen** [comment]
Does it integrate with Jenkins?

**Comment by fdlk** [comment]
I'd expect it to.
On my machine maven clean install site works fine again.
Or is there something else that should work?

**Comment by dennishendriksen** [comment]
The visualization of code coverage in Jenkins for the molgenis-reports project.

**Comment by djvanenckevort** [comment]
There is a plugin for Jenkins for JaCoCo code coverage visualization (JaCoCo Plugin <https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin>).

> Op 12 jan. 2015, om 10:18 heeft Dennis Hendriksen <notifications@github.com> het volgende geschreven:
> 
> The visualization of code coverage in Jenkins for the molgenis-reports project.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/molgenis/molgenis/pull/2291#issuecomment-69544158>.
> 

David van Enckevort
Technical Project Leader
+31 (0)6 54 33 22 76
Skype: enckevort76

**Comment by fdlk** [comment]
Shall I try and update jenkins with the plugin after you merge this?

**Comment by dennishendriksen** [comment]
That would be great :-)

**Pull request merged**
