### PR TITLE
Added DataType conversion ITs

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
Depends on #5589

### CODE REVIEW

**Comment by dennishendriksen** [comment]
Please rebase with molgenis/2.0 and pick d72a463

**Comment by dennishendriksen** [comment]
Create a separate PR for 	#5511, use the name of the issue in your commit message so that is more meaningful: 'Fix #5511 Invalid cached query plan when busily making metadata changes' instead of 'Fix #5511'

**Comment by Mark-de-Haan** [comment]
If I put the fix in a separate then most of the tests will fail

**Comment by dennishendriksen** [comment]
Then first merge the bug fix pull request, then merge the integration tests pull request.

**Comment by Mark-de-Haan** [comment]
test this please

**Pull request merged**
