### PR TITLE
Clean up theme administration

### PR DESCRIPTION
**Pull request by fdlk**
TODO:
- [x] Fix the theme manager
- [x] Add fonts to molgenis-theme, see https://github.com/molgenis/molgenis-theme/pull/6
- [x] Remove temporary font repository URL from theme manager and point back at @molgenis/molgenis-theme

In meanwhile you can preview themes-with-fonts if you select one in the theme manager.
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] Migration step added in case of breaking change
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by jvanveen** [comment]
[#7600 Continued - Frontend UI Consistency FTW: Cleanup Molgenis stylesheets](https://trello.com/c/JVfclHhY/302-7600-continued-frontend-ui-consistency-ftw-cleanup-molgenis-stylesheets)

**Comment by jvanveen** [comment]
Can we use molgenis/refactor/7600-theme-cleanup instead? its a bit easier to commit to a common branch.

**Comment by jvanveen** [comment]
Moved to molgenis upstream branch in order to apply changes. Please see PR https://github.com/molgenis/molgenis/pull/9108/

**Comment by fdlk** [comment]
[Jeroen's theme remove PR, the molgenis half](https://trello.com/c/zfeVPANZ/563-jeroens-theme-remove-pr-the-molgenis-half)

**Pull request closed without merging**
