### PR TITLE
Fix #2754 Sorting on the ID attribute in the dataexplorer throws an error, Fix #3309 ElasticsearchRepository.rebuildIndex does not rebuild index

### LINKED ISSUE #2754: Sorting on the ID attribute in the dataexplorer throws an error
## Tested on: Molgenis01, Chrome
- Go to the data explorer and view TypeTest
- Try to sort on the id column

Expected: The column is sorted
Result: An error is thrown and the pager breaks

`Error! Failed to execute phase [query_fetch], all shards failed; shardFailures {[EN447yWHTH-6jJpbV3UCvA][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]: query[ConstantScore(cache(+_type:TypeTest +org.elasticsearch.index.search.nested.NonNestedDocsFilter@9f3b818d))],from[0],size[18],sort[]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }`

### LINKED ISSUE #3309: ElasticsearchRepository.rebuildIndex does not rebuild index
ElasticsearchRepository.rebuildIndex should reindex documents from their source, which is stored in Elasticsearch:

```
@Override
public void rebuildIndex()
{
	// Do nothing
	// FIXME reindex from source documents
	// Do not throw UnsupportedOperationException here because reindexing of repos at startup will fail
}
```

This is important when changing for example analyzer or tokenizer settings.

### PR DESCRIPTION
**Pull request by jjettenn**
Fix sorting by using disk-based "fielddata" instead of in-memory "fielddata"

### CODE REVIEW

**Comment by dennishendriksen** [comment]
This will not fix sorting for existing data sets. Is it feasible to create a migration step that update the mappings and resolves the issue for existing data sets?

**Comment by jjettenn** [comment]
It is not possible to update the mapping parameter doc_values to true:
###Updating field mapping
    In general, the mapping for existing fields cannot be updated. There are some exceptions to this rule.     For instance:

* new properties can be added to Object datatype fields.
* new multi-fields can be added to existing fields.
* doc_values can be disabled, but not enabled.
* the ignore_above parameter can be updated."

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html

In version 2.0 of elastic it is the doc_values = true is the default setting.
https://www.elastic.co/guide/en/elasticsearch/reference/current/doc-values.html

**Comment by dennishendriksen** [comment]
So we have to throw away the mappings and indexed data by reindexing data. But keep in mind #3309.

**Comment by fdlk** [comment]
test this please

**Comment by jjettenn** [comment]
You can test this:
1. by changing the backend of app\src\test\resources\xls\emx_all_datatypes.xlsx to ElasticSearch and try to reindex via the index manager.
Migrating to migration 23

**Comment by dennishendriksen** [comment]
test this please

**Comment by jjettenn** [comment]
Fixed migration. Ready for review and test.

**Comment by jjettenn** [comment]
test this please

**Comment by tommydeboer** [comment]
The app won't start anymore after the migration:

```
Caused by: java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:928) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2053) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3543) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:491) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3245) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2413) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2836) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2313) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:703) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 82 common frames omitted
```

**Comment by jjettenn** [comment]
I would like to reproduce this error message. Which data set did you use?

**Comment by jjettenn** [comment]
test this please

**Comment by jjettenn** [comment]
SET @@global.sort_buffer_size=XXXX;

**Comment by jjettenn** [comment]
test this please

**Pull request merged**
